baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Mikaela Docs Example'
theme = 'pixyll'

[[params.social]]
    icon      = "github" # icon name without the 'fa-'
    icon_pack = "fab"
    url       = "https://github.com/apreshill/apero"
